def mainMenu():
    print("Hello, Please enter any number from 1-9.")
    print("Press Q to Quit")
    a=input("Your choice: ")
    a=str(a)
    if a=="Q":
        print("Thank you for using")
        input()
        exit()
    elif a=="q":
        print("Thank you for using")
        input()
        exit()    
    a=int(a)
    if a<10:
        print(a, "+",a , "=", a+a)
        input()
        print(a+a, "+",a, "=", a+a+a)
        input()
        print(a+a+a, "×", 2, "=",(a+a+a)*2)
        input()
        print((a+a+a)*2, "-", a, "=", ((a+a+a)*2)-a)
        input()
        print(((a+a+a)*2)-a, "÷", a, "=", ((((a+a+a)*2)-a)/a))
        input()
        print((((a+a+a)*2)-a)/a, "×", 10, "=", ((((a+a+a)*2)-a)/a)*10)
        input()
        print((((a+a+a)*2)-a)/a*10, "+", (((a+a+a)*2)-a)/a*10, "=", (((a+a+a)*2)-a)/a*10*2)
        input()
        print("Thank you!")
        input()
        mainMenu()
    elif a>10:
        print("Please type any number from 1-9.")
        input()
        mainMenu()
print(mainMenu())
