def main():
    print("Type this number in this place.")
    print("        |")
    print("        |")
    print("        \/")
    print("        0 ")
    print("     0 ___")
    print("        0 ")
    b = int(input("Your choice: "))
    print("       0 ")
    print("     0___")
    print("       0 ")
    print("      /\ ")
    print("       | ")
    print("       | ")
    print("Type this number in this place.")
    c = int(input("Your choice: "))
    print("                                     0  ")
    print("Type this number in this place.-->0____ ")
    print("                                     0  ")
    e =  int(input("Your choice: "))
    print(c*e+b)
    print("___")
    print(c)
    input("")
    mainMenu()

def menu():
    print("Type this number in this place.")
    print("  |")
    print("  |")
    print("  \/")
    print("  0")
    print("______")
    print("  0  ")
    d = int(input("Your choice: "))
    print("  0")
    print("_____")
    print("  0 ")
    print(" /\ ")
    print("  | ")
    print("  | ")
    print("Type this number in this place.")
    g = int(input("Your choice: "))
    print("   ",d%g)
    print(d/g,"___")
    print("     ",g)
    input("")
    mainMenu()

def mainMenu():
    print("1) Express mixed fraction as imporper fraction.")
    print("2) Express improper fraction as mixed fraction.")
    h = int(input("Your choice: "))
    if h==1:
        main()
    if h==2:
        menu()
    else:
        mainMenu()
print(mainMenu())

